language: node_js
sudo: required
node_js:
  - 8.11.1
github-token: $access_token
cache:
  directories:
    - node_modules
script:
    - set -e

    - npm run docs:build

    - cd docs/.vuepress/dist


    - git init
    - git add -A
    - git commit -m 'deploy'

    - git push -f git@github.com:$access_token/Messiahhh.github.io.git master
    - cd -
branch: master
