language: node_js
sudo: required
node_js:
  - 8.11.1
cache:
  directories:
    - node_modules
script:
  - ./deploy.sh
  - git push -f git@github.com:$access_token/Messiahhh.github.io.git master
  - cd -
after_success:
  - echo "travis ci works"
branch: master
